title: Ahmed Rabie
logo: https://github.com/AhmedRabie01/AhmedRabie.github.io/blob/main/Untitled%20design%20(4).png
description: Data Scientis | Data Analyst 
# show_downloads: true
theme: jekyll-theme-minimal
